{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "090d7a38-d924-4a4c-be8f-a791bbcf5420",
   "metadata": {},
   "source": [
    "Q1. Explain why we have to use the Exception class while creating a Custom Exception.\n",
    "\n",
    "Ans--"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0e1e2b3c-2869-4c12-b0ab-9de0f9374016",
   "metadata": {},
   "source": [
    "When creating a custom exception in a programming language, it is important to use the Exception class as the base class for the following reasons:\n",
    "\n",
    "1.Inheritance: The Exception class is designed to be the base class for all exceptions in the language. By deriving your custom exception class from the Exception class, you inherit all the necessary properties and behaviors that are expected from an exception. This includes features like stack trace information, error message handling, and the ability to catch and handle exceptions using try-catch blocks.\n",
    "\n",
    "2.Consistency: By using the Exception class as the base class for custom exceptions, you ensure consistency with the exception hierarchy of the programming language. It makes it easier for other developers who are familiar with the standard exception hierarchy to understand and work with your custom exception.\n",
    "\n",
    "3.Catching and handling: The Exception class provides a common catch-all mechanism for handling exceptions. When you raise a custom exception derived from the Exception class, you can catch it using a catch block that catches exceptions of type Exception. This allows you to handle your custom exception along with other standard exceptions in a unified manner.\n",
    "\n",
    "4.Library compatibility: Many libraries and frameworks in the programming language ecosystem are designed to work with exceptions derived from the Exception class. By using the Exception class as the base class for your custom exception, you ensure compatibility with these libraries and frameworks. It allows you to seamlessly integrate your custom exception into existing error handling mechanisms and practices.\n",
    "\n",
    "5.Code readability: When other developers read your code, they will immediately recognize that your custom class is an exception by seeing its inheritance from the Exception class. It improves code readability and makes it easier for other developers to understand the purpose and usage of your custom exception.\n",
    "\n",
    "Using the Exception class as the base class for a custom exception provides consistency, inheritance of necessary properties and behaviors, compatibility with existing libraries and frameworks, unified handling, and improved code readability."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cd046693-ff80-4da6-ac32-8783ff6ebad3",
   "metadata": {},
   "source": [
    "Q2. Write a python program to print Python Exception Hierarchy.\n",
    "\n",
    "Ans--"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "6c049d57-a029-4a3b-9366-3e4b1b5289df",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "BaseException\n",
      "    Exception\n",
      "        TypeError\n",
      "            FloatOperation\n",
      "            MultipartConversionError\n",
      "        StopAsyncIteration\n",
      "        StopIteration\n",
      "        ImportError\n",
      "            ModuleNotFoundError\n",
      "            ZipImportError\n",
      "        OSError\n",
      "            ConnectionError\n",
      "                BrokenPipeError\n",
      "                ConnectionAbortedError\n",
      "                ConnectionRefusedError\n",
      "                ConnectionResetError\n",
      "                    RemoteDisconnected\n",
      "            BlockingIOError\n",
      "            ChildProcessError\n",
      "            FileExistsError\n",
      "            FileNotFoundError\n",
      "            IsADirectoryError\n",
      "            NotADirectoryError\n",
      "            InterruptedError\n",
      "                InterruptedSystemCall\n",
      "            PermissionError\n",
      "            ProcessLookupError\n",
      "            TimeoutError\n",
      "            UnsupportedOperation\n",
      "            itimer_error\n",
      "            herror\n",
      "            gaierror\n",
      "            SSLError\n",
      "                SSLCertVerificationError\n",
      "                SSLZeroReturnError\n",
      "                SSLWantWriteError\n",
      "                SSLWantReadError\n",
      "                SSLSyscallError\n",
      "                SSLEOFError\n",
      "            Error\n",
      "                SameFileError\n",
      "            SpecialFileError\n",
      "            ExecError\n",
      "            ReadError\n",
      "            URLError\n",
      "                HTTPError\n",
      "                ContentTooShortError\n",
      "            BadGzipFile\n",
      "        EOFError\n",
      "            IncompleteReadError\n",
      "        RuntimeError\n",
      "            RecursionError\n",
      "            NotImplementedError\n",
      "                ZMQVersionError\n",
      "                StdinNotImplementedError\n",
      "            _DeadlockError\n",
      "            BrokenBarrierError\n",
      "            BrokenExecutor\n",
      "                BrokenThreadPool\n",
      "            SendfileNotAvailableError\n",
      "            ExtractionError\n",
      "            VariableError\n",
      "        NameError\n",
      "            UnboundLocalError\n",
      "        AttributeError\n",
      "            FrozenInstanceError\n",
      "        SyntaxError\n",
      "            IndentationError\n",
      "                TabError\n",
      "        LookupError\n",
      "            IndexError\n",
      "            KeyError\n",
      "                NoSuchKernel\n",
      "                UnknownBackend\n",
      "            CodecRegistryError\n",
      "        ValueError\n",
      "            UnicodeError\n",
      "                UnicodeEncodeError\n",
      "                UnicodeDecodeError\n",
      "                UnicodeTranslateError\n",
      "            UnsupportedOperation\n",
      "            JSONDecodeError\n",
      "            SSLCertVerificationError\n",
      "            Error\n",
      "            UnsupportedDigestmodError\n",
      "            IllegalMonthError\n",
      "            IllegalWeekdayError\n",
      "            ParserError\n",
      "            ClassNotFound\n",
      "            ClipboardEmpty\n",
      "            MessageDefect\n",
      "                NoBoundaryInMultipartDefect\n",
      "                StartBoundaryNotFoundDefect\n",
      "                CloseBoundaryNotFoundDefect\n",
      "                FirstHeaderLineIsContinuationDefect\n",
      "                MisplacedEnvelopeHeaderDefect\n",
      "                MissingHeaderBodySeparatorDefect\n",
      "                MultipartInvariantViolationDefect\n",
      "                InvalidMultipartContentTransferEncodingDefect\n",
      "                UndecodableBytesDefect\n",
      "                InvalidBase64PaddingDefect\n",
      "                InvalidBase64CharactersDefect\n",
      "                InvalidBase64LengthDefect\n",
      "                HeaderDefect\n",
      "                    InvalidHeaderDefect\n",
      "                    HeaderMissingRequiredValue\n",
      "                    NonPrintableDefect\n",
      "                    ObsoleteHeaderDefect\n",
      "                    NonASCIILocalPartDefect\n",
      "                    InvalidDateDefect\n",
      "            MacroToEdit\n",
      "            InvalidFileException\n",
      "            UnequalIterablesError\n",
      "            InvalidVersion\n",
      "            _InvalidELFFileHeader\n",
      "            InvalidWheelFilename\n",
      "            InvalidSdistFilename\n",
      "            InvalidSpecifier\n",
      "            InvalidMarker\n",
      "            UndefinedComparison\n",
      "            UndefinedEnvironmentName\n",
      "            InvalidRequirement\n",
      "                RequirementParseError\n",
      "            InvalidVersion\n",
      "        AssertionError\n",
      "        ArithmeticError\n",
      "            FloatingPointError\n",
      "            OverflowError\n",
      "            ZeroDivisionError\n",
      "                DivisionByZero\n",
      "                DivisionUndefined\n",
      "            DecimalException\n",
      "                Clamped\n",
      "                Rounded\n",
      "                    Underflow\n",
      "                    Overflow\n",
      "                Inexact\n",
      "                    Underflow\n",
      "                    Overflow\n",
      "                Subnormal\n",
      "                    Underflow\n",
      "                DivisionByZero\n",
      "                FloatOperation\n",
      "                InvalidOperation\n",
      "                    ConversionSyntax\n",
      "                    DivisionImpossible\n",
      "                    DivisionUndefined\n",
      "                    InvalidContext\n",
      "        SystemError\n",
      "            CodecRegistryError\n",
      "        ReferenceError\n",
      "        MemoryError\n",
      "        BufferError\n",
      "        Warning\n",
      "            UserWarning\n",
      "                GetPassWarning\n",
      "                FormatterWarning\n",
      "            EncodingWarning\n",
      "            DeprecationWarning\n",
      "                ProvisionalWarning\n",
      "            PendingDeprecationWarning\n",
      "            SyntaxWarning\n",
      "            RuntimeWarning\n",
      "                ProactorSelectorThreadWarning\n",
      "                UnknownTimezoneWarning\n",
      "                PEP440Warning\n",
      "            FutureWarning\n",
      "                ProvisionalCompleterWarning\n",
      "            ImportWarning\n",
      "            UnicodeWarning\n",
      "            BytesWarning\n",
      "            ResourceWarning\n",
      "            DeprecatedTzFormatWarning\n",
      "            PkgResourcesDeprecationWarning\n",
      "        _OptionError\n",
      "        _Error\n",
      "        error\n",
      "        Verbose\n",
      "        Error\n",
      "        SubprocessError\n",
      "            CalledProcessError\n",
      "            TimeoutExpired\n",
      "        TokenError\n",
      "        StopTokenizing\n",
      "        ClassFoundException\n",
      "        EndOfBlock\n",
      "        TraitError\n",
      "        Error\n",
      "        Error\n",
      "            CancelledError\n",
      "            TimeoutError\n",
      "            InvalidStateError\n",
      "        _GiveupOnSendfile\n",
      "        error\n",
      "        Incomplete\n",
      "        TimeoutError\n",
      "        InvalidStateError\n",
      "        LimitOverrunError\n",
      "        QueueEmpty\n",
      "        QueueFull\n",
      "        Empty\n",
      "        Full\n",
      "        ArgumentError\n",
      "        ZMQBaseError\n",
      "            ZMQError\n",
      "                ContextTerminated\n",
      "                Again\n",
      "                InterruptedSystemCall\n",
      "            ZMQBindError\n",
      "            NotDone\n",
      "        PickleError\n",
      "            PicklingError\n",
      "            UnpicklingError\n",
      "        _Stop\n",
      "        ArgumentError\n",
      "        ArgumentTypeError\n",
      "        ConfigError\n",
      "            ConfigLoaderError\n",
      "                ArgumentError\n",
      "            ConfigFileNotFound\n",
      "        ConfigurableError\n",
      "            MultipleInstanceError\n",
      "        ApplicationError\n",
      "        error\n",
      "        TimeoutError\n",
      "        error\n",
      "        ReturnValueIgnoredError\n",
      "        KeyReuseError\n",
      "        UnknownKeyError\n",
      "        LeakedCallbackError\n",
      "        BadYieldError\n",
      "        ReturnValueIgnoredError\n",
      "        Return\n",
      "        InvalidPortNumber\n",
      "        error\n",
      "        LZMAError\n",
      "        RegistryError\n",
      "        _GiveupOnFastCopy\n",
      "        Error\n",
      "            NoSectionError\n",
      "            DuplicateSectionError\n",
      "            DuplicateOptionError\n",
      "            NoOptionError\n",
      "            InterpolationError\n",
      "                InterpolationMissingOptionError\n",
      "                InterpolationSyntaxError\n",
      "                InterpolationDepthError\n",
      "            ParsingError\n",
      "                MissingSectionHeaderError\n",
      "        NoIPAddresses\n",
      "        BadZipFile\n",
      "        LargeZipFile\n",
      "        BadEntryPoint\n",
      "        NoSuchEntryPoint\n",
      "        DuplicateKernelError\n",
      "        ErrorDuringImport\n",
      "        NotOneValueFound\n",
      "        CannotEval\n",
      "        OptionError\n",
      "        BdbQuit\n",
      "        Restart\n",
      "        ExceptionPexpect\n",
      "            EOF\n",
      "            TIMEOUT\n",
      "        PtyProcessError\n",
      "        FindCmdError\n",
      "        HomeDirError\n",
      "        ProfileDirError\n",
      "        IPythonCoreError\n",
      "            TryNext\n",
      "            UsageError\n",
      "            StdinNotImplementedError\n",
      "        InputRejected\n",
      "        GetoptError\n",
      "        ErrorToken\n",
      "        PrefilterError\n",
      "        AliasError\n",
      "            InvalidAliasError\n",
      "        Error\n",
      "            InterfaceError\n",
      "            DatabaseError\n",
      "                InternalError\n",
      "                OperationalError\n",
      "                ProgrammingError\n",
      "                IntegrityError\n",
      "                DataError\n",
      "                NotSupportedError\n",
      "        Warning\n",
      "        SpaceInInput\n",
      "        DOMException\n",
      "            IndexSizeErr\n",
      "            DomstringSizeErr\n",
      "            HierarchyRequestErr\n",
      "            WrongDocumentErr\n",
      "            InvalidCharacterErr\n",
      "            NoDataAllowedErr\n",
      "            NoModificationAllowedErr\n",
      "            NotFoundErr\n",
      "            NotSupportedErr\n",
      "            InuseAttributeErr\n",
      "            InvalidStateErr\n",
      "            SyntaxErr\n",
      "            InvalidModificationErr\n",
      "            NamespaceErr\n",
      "            InvalidAccessErr\n",
      "            ValidationErr\n",
      "        ValidationError\n",
      "        EditReadOnlyBuffer\n",
      "        _Retry\n",
      "        InvalidLayoutError\n",
      "        HeightIsUnknownError\n",
      "        ParserSyntaxError\n",
      "        InternalParseError\n",
      "        _PositionUpdatingFinished\n",
      "        SimpleGetItemNotFound\n",
      "        UncaughtAttributeError\n",
      "        HasNoContext\n",
      "        ParamIssue\n",
      "        _JediError\n",
      "            InternalError\n",
      "            WrongVersion\n",
      "            RefactoringError\n",
      "        OnErrorLeaf\n",
      "        InvalidPythonEnvironment\n",
      "        MessageError\n",
      "            MessageParseError\n",
      "                HeaderParseError\n",
      "                BoundaryError\n",
      "            MultipartConversionError\n",
      "            CharsetError\n",
      "        Error\n",
      "        HTTPException\n",
      "            NotConnected\n",
      "            InvalidURL\n",
      "            UnknownProtocol\n",
      "            UnknownTransferEncoding\n",
      "            UnimplementedFileMode\n",
      "            IncompleteRead\n",
      "            ImproperConnectionState\n",
      "                CannotSendRequest\n",
      "                CannotSendHeader\n",
      "                ResponseNotReady\n",
      "            BadStatusLine\n",
      "                RemoteDisconnected\n",
      "            LineTooLong\n",
      "        InteractivelyDefined\n",
      "        KillEmbedded\n",
      "        Error\n",
      "            NoSuchProcess\n",
      "                ZombieProcess\n",
      "            AccessDenied\n",
      "            TimeoutExpired\n",
      "        _Ipv6UnsupportedError\n",
      "        QueueEmpty\n",
      "        QueueFull\n",
      "        DebuggerInitializationError\n",
      "        ExpatError\n",
      "        Error\n",
      "            ProtocolError\n",
      "            ResponseError\n",
      "            Fault\n",
      "        ParseBaseException\n",
      "            ParseException\n",
      "            ParseFatalException\n",
      "                ParseSyntaxException\n",
      "        RecursiveGrammarException\n",
      "        ResolutionError\n",
      "            VersionConflict\n",
      "                ContextualVersionConflict\n",
      "            DistributionNotFound\n",
      "            UnknownExtra\n",
      "        _Error\n",
      "        UnableToResolveVariableException\n",
      "        InvalidTypeInArgsException\n",
      "    GeneratorExit\n",
      "    SystemExit\n",
      "    KeyboardInterrupt\n",
      "    CancelledError\n",
      "    AbortThread\n"
     ]
    }
   ],
   "source": [
    "def print_exception_hierarchy(exception_class, indent=0):\n",
    "    print(' ' * indent + exception_class.__name__)\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, indent + 4)\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    print_exception_hierarchy(BaseException)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1329c407-8a1b-4869-ac40-aa79f825207c",
   "metadata": {},
   "source": [
    "Q3. What errors are defined in the ArithmeticError class? Explain any two with an example.\n",
    "\n",
    "Ans--"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8ec4d524-1108-436c-be9f-0fd21c50aabd",
   "metadata": {},
   "source": [
    "The ArithmeticError class in Python is a base class for arithmetic errors. It serves as a parent class for specific arithmetic-related exception classes. Here are two common errors defined in the ArithmeticError class, along with examples:\n",
    "\n",
    "1.ZeroDivisionError:\n",
    "\n",
    "The ZeroDivisionError is raised when attempting to divide a number by zero.\n",
    "\n",
    "Example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "ff8495ad-638b-41ab-8ba1-bce620007755",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: division by zero\n"
     ]
    }
   ],
   "source": [
    "numerator = 10\n",
    "denominator = 0\n",
    "\n",
    "try:\n",
    "    result = numerator / denominator\n",
    "    print(\"Result:\", result)\n",
    "except ZeroDivisionError as e:\n",
    "    print(\"Error:\", e)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "13c224d5-51c3-4eed-8218-dd0541d784e7",
   "metadata": {},
   "source": [
    "2.OverflowError:\n",
    "\n",
    "The OverflowError is raised when the result of an arithmetic operation exceeds the maximum representable value.\n",
    "\n",
    "Example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "a3684ce6-74c0-44d7-a53c-f35ac96fb401",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result: 9223372036854775808\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "\n",
    "try:\n",
    "    result = sys.maxsize + 1\n",
    "    print(\"Result:\", result)\n",
    "except OverflowError as e:\n",
    "    print(\"Error:\", e)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b4a651d0-3405-4824-a18c-278bfe0a2920",
   "metadata": {},
   "source": [
    "Q4. Why LookupError class is used? Explain with an example KeyError and IndexError.\n",
    "\n",
    "Ans--"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "43773de7-291a-46f9-88f4-d86cbcf8ebee",
   "metadata": {},
   "source": [
    "The LookupError class is a base class in Python used to handle lookup-related errors. It serves as a superclass for more specific lookup-related exceptions such as KeyError and IndexError. The purpose of using the LookupError class is to catch and handle situations where a lookup operation fails due to an invalid key or index.\n",
    "\n",
    "Let's take a closer look at KeyError and IndexError as examples:\n",
    "\n",
    "1.KeyError: This exception is raised when a dictionary is accessed using a key that does not exist. It occurs when you try to access a key that is not present in the dictionary.\n",
    "\n",
    "For instance:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "9c6ac4c3-4203-491f-8a00-b3321f98b320",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The key 'd' does not exist in the dictionary.\n"
     ]
    }
   ],
   "source": [
    "my_dict = {'a': 1, 'b': 2, 'c': 3}\n",
    "\n",
    "try:\n",
    "    value = my_dict['d']  \n",
    "except KeyError:\n",
    "    print(\"The key 'd' does not exist in the dictionary.\")\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "adfb22dc-95ef-4ff9-b775-821eeb099f96",
   "metadata": {},
   "source": [
    "2.IndexError: This exception is raised when a sequence (such as a list or a string) is accessed using an invalid index. It occurs when you try to access an index that is outside the valid range of indices for the sequence.\n",
    "\n",
    "For example:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "197212b5-37fc-4be6-aee6-2d0f6eeaa9ca",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The index 3 is out of range for the list.\n"
     ]
    }
   ],
   "source": [
    "my_list = [1, 2, 3]\n",
    "\n",
    "try:\n",
    "    value = my_list[3]  \n",
    "except IndexError:\n",
    "    print(\"The index 3 is out of range for the list.\")\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e7169ee1-7498-45c3-882f-6a31beed484f",
   "metadata": {},
   "source": [
    "In both cases, KeyError and IndexError are subclasses of LookupError. By catching the LookupError class, you can handle any kind of lookup-related error in a generalized way, or you can catch the specific exceptions (KeyError or IndexError) individually if you want to handle them differently."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "52ecf4fa-9a48-49c4-865e-02c36a680bac",
   "metadata": {},
   "source": [
    "Q5. Explain ImportError. What is ModuleNotFoundError?\n",
    "\n",
    "Ans--"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "75015952-2c1a-48a4-a1ff-c762e3a701d9",
   "metadata": {},
   "source": [
    "In Python, ImportError and ModuleNotFoundError are both exceptions that occur when there are issues with importing modules or packages.\n",
    "\n",
    "1.ImportError: ImportError is a general exception that is raised when an import statement fails to find or load a module. It can occur due to various reasons, such as:\n",
    "\n",
    "a.The module or package you are trying to import does not exist.\n",
    "\n",
    "b.The module or package is not installed in your Python environment.\n",
    "\n",
    "c.There is a syntax error or other issue within the module that prevents it from being imported.\n",
    "\n",
    "When an ImportError occurs, Python raises this exception and provides details about the error, such as the name of the module that failed to import.\n",
    "\n",
    "2.ModuleNotFoundError: ModuleNotFoundError is a specific subclass of ImportError that was introduced in Python 3.6. It is raised when an import statement fails to find the specified module or package. This exception is more specific and informative than the general ImportError, as it clearly indicates that the module or package could not be located.\n",
    "\n",
    "When you encounter a ModuleNotFoundError, it means that the module you are trying to import does not exist in any of the directories listed in the Python's search path (sys.path). This could be due to misspelling the module name or not having the module installed.\n",
    "\n",
    "Example to illustrate these exceptions:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "4dce1fef-aa2b-4a4f-a639-94bed7c8b8ec",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ImportError: No module named 'non_existent_module'\n",
      "ModuleNotFoundError: No module named 'another_non_existent_module'\n"
     ]
    }
   ],
   "source": [
    "try:\n",
    "    import non_existent_module\n",
    "except ImportError as e:\n",
    "    print(f\"ImportError: {e}\")\n",
    "\n",
    "try:\n",
    "    import another_non_existent_module\n",
    "except ModuleNotFoundError as e:\n",
    "    print(f\"ModuleNotFoundError: {e}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b39d1abf-73bd-4e07-830c-9e04eb4d3488",
   "metadata": {},
   "source": [
    "Q6. List down some best practices for exception handling in python.\n",
    "\n",
    "Ans--"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "873ee094-0d2b-41b7-92d2-99dfc249279e",
   "metadata": {},
   "source": [
    "Exception handling is an essential aspect of writing robust and reliable Python code. Here are some best practices for exception handling in Python:\n",
    "\n",
    "1.Be specific with exception handling: Catch only the exceptions that you expect and know how to handle. Avoid using a generic except block, as it can hide errors and make debugging difficult. Instead, catch specific exceptions and handle them appropriately.\n",
    "\n",
    "2.Use multiple except blocks: If you anticipate different types of exceptions, use separate except blocks for each exception type. This allows you to handle different exceptions differently and provides better control over the program flow.\n",
    "\n",
    "3.Handle exceptions gracefully: When an exception occurs, handle it gracefully by providing informative error messages or taking appropriate actions. You can log the error, display a user-friendly message, or attempt to recover from the exception if possible.\n",
    "\n",
    "4.Avoid bare except blocks: A bare except block without any exception type specified can catch any exception, including system-exiting exceptions like SystemExit and KeyboardInterrupt. This can lead to unexpected behavior and make it harder to identify and debug issues. Always specify the exception type(s) you expect to handle.\n",
    "\n",
    "5.Use finally block for cleanup: If you need to perform certain cleanup operations, such as closing files or releasing resources, regardless of whether an exception occurred or not, use a finally block. The code within the finally block will execute regardless of whether an exception was raised.\n",
    "\n",
    "6.Reraise exceptions selectively: If you catch an exception but cannot handle it properly, consider reraising the exception using the raise statement without any arguments. This allows the exception to propagate up the call stack, giving higher-level code the opportunity to handle it appropriately.\n",
    "\n",
    "7.Use context managers (with statement): Context managers provide a clean and concise way to handle resources that need to be properly managed, such as files or network connections. They automatically handle exceptions and ensure that resources are properly released, even if an exception occurs.\n",
    "\n",
    "8.Use custom exception classes: In addition to built-in exceptions, you can define your own exception classes to represent specific types of errors in your application. This helps in making your code more organized, easier to read, and allows for better exception handling.\n",
    "\n",
    "9.Use logging for error tracking: Instead of printing error messages directly to the console, consider using a logging library like Python's built-in logging module. Logging provides more flexibility and control over error messages, allowing you to track and manage errors effectively.\n",
    "\n",
    "10.Test exception handling: Write unit tests to specifically test exception handling in your code. This helps ensure that exceptions are raised and handled as expected, and it gives you confidence in the robustness of your code."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "427563ff-bd4d-47be-ac42-70618649d7ae",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
